config/routes.rb
Rails.application.routes.draw do
  resources :images

  root 'main#index'
  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :users
    resources :themes
    resources :values
    get 'main/index'
    get 'main/help'
    get 'main/contacts'
    get 'main/about'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#delete'
    match 'works', to: 'works#index', via: 'get'
    match 'choose_image', to: 'works#choose_image', via: :get
    match 'display_theme', to: 'works#display_theme', via: :post
    match 'choose_theme', to: 'works#choose_theme', via: :get
    match 'results_list', to: 'works#results_list', via: :get

    # Api definition
    namespace :api, defaults: {format: :json} do
      match 'next_image', to: 'api#next_image', via: 'get'
      match 'prev_image', to: 'api#prev_image', via: 'get'
      match 'save_value', to: 'api#save_value', via: :get
    end
  end
end

app/models/theme.rb
class Theme < ApplicationRecord
  has_many :images
  scope :find_theme_id, -> (theme) { find_by_name(theme) }
end

app/controllers/themes_controller.rb
class ThemesController < ApplicationController
  before_action :set_theme, only: [:show, :edit, :update, :destroy]

  # GET /themes
  # GET /themes.json
  def index
    @themes = Theme.all
  end

  # GET /themes/1
  # GET /themes/1.json
  def show
    @theme = Theme.find(params[:id])
  end

  # GET /themes/new
  def new
    @theme = Theme.new
  end

  # GET /themes/1/edit
  def edit
    @theme = Theme.find(params[:id])
  end

  # POST /themes
  # POST /themes.json
  def create
    @theme = Theme.new(theme_params)

    @theme.save
    redirect_to @theme
  end

  # PATCH/PUT /themes/1
  # PATCH/PUT /themes/1.json
  def update
    respond_to do |format|
      if @theme.update(theme_params)
        format.html { redirect_to @theme, notice: 'Theme was successfully updated.' }
        format.json { render :show, status: :ok, location: @theme }
      else
        format.html { render :edit }
        format.json { render json: @theme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /themes/1
  # DELETE /themes/1.json
  def destroy
    @theme.destroy
    respond_to do |format|
      format.html { redirect_to themes_url, notice: 'Theme was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_theme
      @theme = Theme.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def theme_params
      params.require(:theme).permit(:name, :qty_items)
    end
end

app/helpers/themes_helper.rb
module ThemesHelper
end

app/views/themes/_form.html.erb
<%= form_for(theme) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :qty_items %>
    <%= f.number_field :qty_items %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/themes/edit.html.erb
<h1>Editing Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Show', @theme %> |
<%= link_to 'Back', themes_path %>

app/views/themes/index.html.erb
<h1>Listing themes</h1>
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Qty items</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @themes.each do |theme| %>
    <tr>
      <td>
        <%= theme.name %>
      </td>
      <td>
        <%= theme.qty_items %>
      </td>
      <td>
        <%= link_to 'Show', theme %>
      </td>
      <td>
        <%= link_to 'Edit', edit_theme_path(theme) %>
      </td>
      <td>
        <%= link_to 'Destroy', theme_path(theme), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<br/>
<%= link_to 'New Theme', new_theme_path %>

app/views/themes/new.html.erb
<h1>New Theme</h1>

<%= render 'form', theme: @theme %>

<%= link_to 'Back', themes_path %>

app/views/themes/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @theme.name %></h1>
<p><%= @theme.qty_items%></p>

<%# @theme.name.each do |theme| %>
<!--  <h2><%#= link_to theme.name, theme %></h2>-->
<%# end %>

<!--<p id="notice"><%#= notice %></p>-->

<%= link_to 'Edit', edit_theme_path(@theme) %> |
<%= link_to 'Back', themes_path %>
<%= link_to 'Destroy', theme_path(@theme), method: :delete, data: { confirm: 'Are you sure?' } %>