config/routes.rb
Rails.application.routes.draw do
  resources :images

  root 'main#index'
  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :users
    resources :themes
    resources :values
    get 'main/index'
    get 'main/help'
    get 'main/contacts'
    get 'main/about'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#delete'
    match 'works', to: 'works#index', via: 'get'
    match 'choose_image', to: 'works#choose_image', via: :get
    match 'display_theme', to: 'works#display_theme', via: :post
    match 'choose_theme', to: 'works#choose_theme', via: :get
    match 'results_list', to: 'works#results_list', via: :get

    # Api definition
    namespace :api, defaults: {format: :json} do
      match 'next_image', to: 'api#next_image', via: 'get'
      match 'prev_image', to: 'api#prev_image', via: 'get'
      match 'save_value', to: 'api#save_value', via: :get
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :values, dependent: :destroy

  include Gravtastic
  gravtastic


  EMAIL_FORMAT = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true
  validates :email, presence: true, format: { with: EMAIL_FORMAT }, uniqueness: true
  before_save { self.email = email.downcase }
  has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.fetch(:user, {}).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <div class="alert alert-danger" role="alert">
            <%= message %>
          </div>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1"><%= t('views.users.name') %></span>
      </div>
      <%= form.text_field(:name, class: "form-control", placeholder: "Имя пользователя") %>
    </div>

    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">@</span>
      </div>
      <%= form.email_field(:email, class: "form-control", placeholder: "Email") %>
    </div>

    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1"><%= t('views.users.password') %></span>
      </div>
      <%= form.password_field(:password, class: "form-control", placeholder: t('views.users.password')) %>
    </div>

    <div class="input-group mb-3">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1"><%= t('views.users.password_confirmation') %></span>
      </div>
      <%= form.password_field(:password_confirmation, class: "form-control", placeholder: t('views.users.password')) %>
    </div>

    <%= form.submit t('views.users.submit'), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %><%= link_to 'Назад', @user, class: "btn btn-light" %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
  <h1><%= t('views.users.new_user')%></h1>
  <%= render 'form', user: @user %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<%= image_tag @user.gravatar_url %>

<h2>Email: <%= @user.email %></h2>
<div class="row">
  <div class="col-sm">
    <%= link_to 'Редактировать аккаунт', edit_user_path(@user), class: "btn btn-primary btn-sm"%>
  </div>
  <div class="col-sm">
    <%= link_to 'Удалить аккаунт', @user, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-outline-danger btn-sm"%>
  </div>
  <div class="col-sm">
    <%= link_to 'Выйти', logout_path, class: "btn btn-outline-primary btn-sm"%>
  </div>
</div>