config/routes.rb
Rails.application.routes.draw do
  resources :images

  root 'main#index'
  scope "/:locale", locale: /#{I18n.available_locales.join("|")}/ do
    resources :users
    resources :themes
    resources :values
    get 'main/index'
    get 'main/help'
    get 'main/contacts'
    get 'main/about'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#delete'
    match 'works', to: 'works#index', via: 'get'
    match 'choose_image', to: 'works#choose_image', via: :get
    match 'display_theme', to: 'works#display_theme', via: :post
    match 'choose_theme', to: 'works#choose_theme', via: :get
    match 'results_list', to: 'works#results_list', via: :get

    # Api definition
    namespace :api, defaults: {format: :json} do
      match 'next_image', to: 'api#next_image', via: 'get'
      match 'prev_image', to: 'api#prev_image', via: 'get'
      match 'save_value', to: 'api#save_value', via: :get
    end
  end
end

app/views/shared/_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p>Artem Pavskii © 2020 | <%= link_to t('global.footer.contacts'), main_contacts_path %> |
    <% if I18n.locale == :ru %>
      <%= link_to '🇷🇺', locale: :en %>
    <% else %>
      <%= link_to '🇺🇸', locale: :ru %>
    <% end %>
    </p>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">THE GREAT APP</h3>
    <nav class="nav nav-masthead justify-content-center">
      <%= link_to t('global.header.main_index'), main_index_path, class: "nav-link #{'active' if current_page? main_index_path}" %>
      <%= link_to t('global.header.about'), main_about_path, class: "nav-link #{'active' if current_page? main_about_path}" %>
      <%= link_to t('global.header.help'), main_help_path, class: "nav-link #{'active' if current_page? main_help_path}" %>
      <% if current_user %>
        <%= link_to t('global.header.exit'), logout_path, class: "nav-link" %> <i class="fas fa-sign-out-alt"></i>
        <%= link_to image_tag(current_user.gravatar_url, class: "gravatar"), current_user %>
      <% end %>
    </nav>
  </div>
</header>